title = "species parameters"

[debug]
class_name = "mammals"
auc_threshold = 0.7
boyce_threshold = 0.5
min_area_threshold = 1.0
method_threshold = "Maximum training sensitivity plus specificity Cloglog threshold"

[release]
class_name = "all"
auc_threshold = 0.7
boyce_threshold = 0.5
min_area_threshold = 1.0
method_threshold = "Maximum training sensitivity plus specificity Cloglog threshold"
